version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tech_hub_training
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: tech_hub_training
      DB_PORT: 5432
    ports:
      - "5000:5000"
    command: ["python", "fetch_title.py"]

volumes:
  postgres_data:
